#!/usr/bin/env python3
"""gen_ducktales.py -- mod/src/DuckTalesData.cs, the DuckTales pack's recipe.

What the port needs to rebuild Disney Crossy Road's DuckTales characters in
the SEA game: for each character its id, English name, scales, animation
frames (mesh GUIDs and material names), hop sound keys and config line; and
the DuckTales sound mappings (names and clip GUIDs). References only: every
mesh, sound and texture is read at run time from the player's own copy of
Disney Crossy Road (dcr.apk). The inputs are made from that APK by the
scripts in tools/mod/ducktales/ (Unity SerializedFile reader, Character and
AudioController layouts):

  python3 tools/mod/gen_ducktales.py <recipe.json> <audio_maps.json>

MIT.
"""
import json
import os
import re
import sys


def cs(s):
    return '"' + (s or "").replace("\\", "\\\\").replace('"', '\\"') + '"'


def display_name(s):
    """The English name as the game's font shows it: JSON escapes the extractor
    left in (Peghook\\u2019s) decoded, typographic apostrophes as plain ones (the
    SEA text writes "Sorcerer's Apprentice Mickey" that way)."""
    s = re.sub(r"\\u([0-9a-fA-F]{4})", lambda m: chr(int(m.group(1), 16)), s or "")
    return s.replace("\u2019", "'").replace("\u2018", "'")


def anims(lst):
    if not lst:
        return "new A[0]"
    out = []
    for a in lst:
        frames = ", ".join("new F(%s, %s, %s)" % (cs(f["guid"]), cs(f["material"]), "true" if f.get("inSEA") else "false")
                           for f in a["frames"])
        out.append("new A(%s, %s, %sf, new F[] { %s })" % (cs(a["name"]), cs(a["next"]), repr(float(a["speed"])), frames))
    return "new A[] {\n                " + ",\n                ".join(out) + " }"


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    chars = json.load(open(sys.argv[1]))
    audio = json.load(open(sys.argv[2]))
    L = []
    L.append("// DuckTalesData.cs -- GENERATED by tools/mod/gen_ducktales.py; do not edit.")
    L.append("// References into Disney Crossy Road (the world-wide edition) that the player supplies")
    L.append("// as dcr.apk: mesh and sound GUIDs, names, scales. No game data is in here.")
    L.append("namespace DcrMod")
    L.append("{")
    L.append("    public static class DuckTalesData")
    L.append("    {")
    L.append("        public class F { public string Guid, Mat; public bool InSea; public F(string g, string m, bool s) { Guid = g; Mat = m; InSea = s; } }")
    L.append("        public class A { public string Name, Next; public float Speed; public F[] Frames; public A(string n, string x, float s, F[] f) { Name = n; Next = x; Speed = s; Frames = f; } }")
    L.append("        public class C")
    L.append("        {")
    L.append("            public string Id, Name, Anim, Prefab, Hop, GenericHop, Scream, FirstHop, Config;")
    L.append("            public float Scale, Zoom;")
    L.append("            public int IdleBehaviour;")
    L.append("            public bool RandomPitch;")
    L.append("            public A[] Select, Idle, Ready, Jump, AltJump, Dead, Blocked, Additional;")
    L.append("        }")
    L.append("        public static readonly C[] Chars = {")
    for c in chars:
        a = c["animations"]
        L.append("            new C {")
        L.append("                Id = %s, Name = %s, Anim = %s, Prefab = %s," % (cs(c["id"]), cs(display_name(c["nameEN"])), cs(c["anim"]), cs(c["dcrPrefab"])))
        L.append("                Hop = %s, GenericHop = %s, Scream = %s, FirstHop = %s," % (cs(c["hopAudioKey"]), cs(c["genericHopsKey"]), cs(c["audioScreamKey"]), cs(c["firstHopKey"])))
        L.append("                Scale = %rf, Zoom = %rf, IdleBehaviour = %d, RandomPitch = %s," % (float(c["selectScreenScale"]), float(c["selectedZoomPercentage"]), int(c["idleAnimationBehaviour"]), "true" if c["randomPitchHop"] else "false"))
        L.append("                Config = %s," % cs(c["configLine"]))
        for k, n in (("Select", "selectAnimations"), ("Idle", "idleAnimations"), ("Ready", "readyAnimations"), ("Jump", "jumpAnimations"),
                     ("AltJump", "altJumpAnimations"), ("Dead", "deadAnimations"), ("Blocked", "blockedAnimations"), ("Additional", "additionalAnimations")):
            L.append("                %s = %s," % (k, anims(a.get(n))))
        L.append("            },")
    L.append("        };")
    L.append("        public class S { public string Name; public int Sorting, Mixer; public string[] Guids; public S(string n, int s, int m, string[] g) { Name = n; Sorting = s; Mixer = m; Guids = g; } }")
    L.append("        // Mixer: 0 = the characters' group, 1 = the effects group (as in the SEA game's own mappings)")
    L.append("        public static readonly S[] Sounds = {")
    for m in audio["dcr"]:
        if not m["name"].startswith("Ducktales-"):
            continue
        L.append("            new S(%s, 115, %d, new[] { %s })," % (cs(m["name"]), 0 if m["mixer"][1] == 486 else 1, ", ".join(cs(g) for g in m["sounds"])))
    L.append("        };")
    L.append("        // universe 115's own clips for mappings every universe has")
    L.append("        public static readonly string[][] Overrides = {")
    for m in audio["dcr"]:
        for o in m["overrides"]:
            if o["key"] == 115:
                L.append("            new[] { %s, %s }," % (cs(m["name"]), ", ".join(cs(g) for g in o["sounds"])))
    L.append("        };")
    L.append("    }")
    L.append("}")
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, "..", "..", "mod", "src", "DuckTalesData.cs")
    open(out, "w").write("\n".join(L) + "\n")
    print("gen_ducktales.py: %d characters, %d sound mappings -> %s" % (len(chars), sum(1 for m in audio["dcr"] if m["name"].startswith("Ducktales-")), os.path.normpath(out)))


if __name__ == "__main__":
    main()
