#!/usr/bin/env python3
"""make_button_icons.py -- the Switch's buttons as white pictures, for the
port's button hints (mod/src/Ui.cs: the multiplayer room's legend, the
character select's, the pause screen's).

The drawing is the Sonic & SEGA All-Stars Racing port's (its
tools/make_button_icons.py): the face buttons, + and - as white discs with the
letter cut in dark blue, the shoulders as white rounded bars, the sticks as
white rings, the D-pad as a white cross -- all with a thin dark rim so they
read on light backgrounds too. Written here as a C# file, the row as a PNG in
base64 and where each button is in it:

  mod/src/ButtonIconsData.cs      (generated; every button 96 pixels high)
The letters: DejaVu Sans Bold (tools/mod/fonts, free licence: LICENSE_DEJAVU).
Run it again after changing the drawing (needs Pillow).
"""
import base64
import io
import os

from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
FONT = os.path.join(HERE, 'fonts', 'DejaVuSans-Bold.ttf')

H = 96   # master height
SS = 4   # drawn at 4x, then reduced: smooth edges
WHITE = (255, 255, 255, 255)
INK = (20, 38, 84, 255)      # the game's dark blue, for the letters
RIM = (10, 20, 46, 150)      # a thin dark rim

BUTTONS = [  # (name, kind, label)
    ('A', 'round', 'A'), ('B', 'round', 'B'), ('X', 'round', 'X'), ('Y', 'round', 'Y'),
    ('PLUS', 'round', '+'), ('MINUS', 'round', '-'), ('L', 'shoulder', 'L'), ('R', 'shoulder', 'R'),
    ('ZL', 'trigger', 'ZL'), ('ZR', 'trigger', 'ZR'), ('LSTICK', 'stick', 'L'), ('RSTICK', 'stick', 'R'),
    ('DPAD', 'dpad', ''),
]


def font(px):
    return ImageFont.truetype(FONT, px)


def centred(d, box, text, px, fill):
    f = font(px)
    l, t, r, b = d.textbbox((0, 0), text, font=f)
    x0, y0, x1, y1 = box
    d.text(((x0 + x1 - (r - l)) / 2 - l, (y0 + y1 - (b - t)) / 2 - t), text, font=f, fill=fill)


def draw(kind, label):
    h = H * SS
    w = {'round': h, 'stick': h, 'dpad': h, 'shoulder': int(h * 1.25), 'trigger': int(h * 1.45)}[kind]
    im = Image.new('RGBA', (w, h), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    m = int(h * 0.06)   # margin
    rim = int(h * 0.035)
    if kind == 'round':
        d.ellipse((m - rim, m - rim, w - m + rim, h - m + rim), fill=RIM)
        d.ellipse((m, m, w - m, h - m), fill=WHITE)
        if label == '+':
            t = int(h * 0.09)
            c = h // 2
            d.rectangle((c - int(h * 0.24), c - t, c + int(h * 0.24), c + t), fill=INK)
            d.rectangle((c - t, c - int(h * 0.24), c + t, c + int(h * 0.24)), fill=INK)
        elif label == '-':
            t = int(h * 0.09)
            c = h // 2
            d.rectangle((c - int(h * 0.24), c - t, c + int(h * 0.24), c + t), fill=INK)
        else:
            centred(d, (m, m, w - m, h - m), label, int(h * 0.56), INK)
    elif kind in ('shoulder', 'trigger'):
        r = int(h * 0.30)
        box = (m, int(h * 0.16), w - m, h - int(h * 0.16))
        d.rounded_rectangle((box[0] - rim, box[1] - rim, box[2] + rim, box[3] + rim), r + rim, fill=RIM)
        d.rounded_rectangle(box, r, fill=WHITE)
        centred(d, box, label, int(h * 0.46), INK)
    elif kind == 'stick':
        d.ellipse((m - rim, m - rim, w - m + rim, h - m + rim), fill=RIM)
        d.ellipse((m, m, w - m, h - m), fill=WHITE)
        i = int(h * 0.17)
        d.ellipse((m + i, m + i, w - m - i, h - m - i), fill=INK)
        centred(d, (m + i, m + i, w - m - i, h - m - i), label, int(h * 0.38), WHITE)
    elif kind == 'dpad':
        t = int(h * 0.17)   # half the arm's width
        c = h // 2
        a = h // 2 - m      # arm length
        for rr, col in ((rim, RIM), (0, WHITE)):
            d.rounded_rectangle((c - a - rr, c - t - rr, c + a + rr, c + t + rr), int(h * 0.05) + rr, fill=col)
            d.rounded_rectangle((c - t - rr, c - a - rr, c + t + rr, c + a + rr), int(h * 0.05) + rr, fill=col)
        d.ellipse((c - int(t * 0.55), c - int(t * 0.55), c + int(t * 0.55), c + int(t * 0.55)), fill=(200, 208, 224, 255))
    return im.resize((w // SS, H), Image.LANCZOS)


def main():
    pics = [draw(k, l) for _, k, l in BUTTONS]
    total = sum(p.width for p in pics)
    row = Image.new('RGBA', (total, H), (0, 0, 0, 0))
    x = 0
    cells = []
    for p in pics:
        row.paste(p, (x, 0))
        cells.append((x, p.width))
        x += p.width
    buf = io.BytesIO()
    row.save(buf, 'PNG', optimize=True)
    b64 = base64.b64encode(buf.getvalue()).decode('ascii')
    lines = [b64[i:i + 100] for i in range(0, len(b64), 100)]
    out = os.path.join(ROOT, 'mod', 'src', 'ButtonIconsData.cs')
    with open(out, 'w') as f:
        f.write('// ButtonIconsData.cs -- GENERATED by tools/mod/make_button_icons.py; do not edit.\n')
        f.write('// The Switch\'s buttons, drawn white, in one row %d pixels high (a PNG).\n' % H)
        f.write('namespace DcrMod\n{\n    public static class ButtonIconsData\n    {\n')
        f.write('        public const int Height = %d;\n' % H)
        f.write('        public static readonly string[] Names = { %s };\n' % ', '.join('"%s"' % l if n not in ('LSTICK', 'RSTICK', 'DPAD') else '"%s"' % n for n, _, l in BUTTONS))
        f.write('        public static readonly int[] X = { %s };\n' % ', '.join(str(c[0]) for c in cells))
        f.write('        public static readonly int[] W = { %s };\n' % ', '.join(str(c[1]) for c in cells))
        f.write('        public const string Png =\n' + ' +\n'.join('            "%s"' % l for l in lines) + ';\n')
        f.write('    }\n}\n')
    print('ButtonIconsData.cs: %d x %d, %d buttons, %d bytes of PNG' % (total, H, len(BUTTONS), len(buf.getvalue())))


if __name__ == '__main__':
    main()
