/* GENERATED by tools/offsets/derive_offsets.py -- do not hand-edit.
 *
 *   libunity.so  Unity 5.3.4f1 (Mono)  BuildID 35f7a6933675b8f050169dd4695e1ad563bfd205
 *   libmono.so                              BuildID ?
 *
 * Unity 5.6/2017.4 pace frames with the Choreographer VSYNC path (pumped,
 * not patched); Unity 5.3 has no such path (no VSYNC section below) and
 * paces with eglSwapInterval / targetFrameRate. The engine clock is
 * clock_gettime-backed and correct while awake; the Time hooks exist to
 * freeze it across sleep/HOME. The GC offsets describe Mono bdwgc's
 * tkill-based thread suspend.
 *
 * Every RVA carries the game's own leading words as a guard; consumers
 * verify before writing and SKIP on mismatch.
 */
#ifndef DCR_OFFSETS_H
#define DCR_OFFSETS_H
#include <stdint.h>

typedef struct { const char *name; uint32_t rva; uint32_t guard[4]; } DcrSite;
#define DCR_NSITES(a) ((int)(sizeof(a) / sizeof((a)[0])))

#define DCR_UNITY_BUILD_ID "35f7a6933675b8f050169dd4695e1ad563bfd205"
#define DCR_MONO_BUILD_ID  "?"

/* ===== TIME: 4 TimeManager entry points ===== */
#define DCR_RVA_GetTimeManager           0x0360cb0u
static const uint32_t DCR_GUARD_GetTimeManager[4] = { 0xe92d4800u, 0xe3a00007u, 0xebf65cf8u, 0xe8bd8800u };
#define DCR_RVA_GetRealtimeSinceStartup  0x0360968u
static const uint32_t DCR_GUARD_GetRealtimeSinceStartup[4] = { 0xe92d4010u, 0xe1a04000u, 0xeb06091cu, 0xedd40b26u };
#define DCR_RVA_SetTimeScale             0x03608e8u
static const uint32_t DCR_GUARD_SetTimeScale[4] = { 0xe92d4800u, 0xe24dd010u, 0xee001a10u, 0xed9f1a17u };
#define DCR_RVA_SetFixedDeltaTime        0x03607fcu
static const uint32_t DCR_GUARD_SetFixedDeltaTime[4] = { 0xed9f0a13u, 0xee011a10u, 0xeeb41ac0u, 0xeef1fa10u };

/* TimeManager field layout (Unity 5.3.4f1), read off the getters. */
#define DCR_TM_FIELD_FIXEDDELTA         0x28
#define DCR_TM_FIELD_TIMESCALE          0xbc
#define DCR_TM_FIELD_FRAMECOUNT         0x7c

/* ===== TIME: 10 Time icall bindings (of 19 declared) ===== */
static const DcrSite DCR_TIME_SITES[] = {
  { "get_time", 0x07d6984u, { 0xe92d4800u, 0xebee28c8u, 0xedd00b16u, 0xeeb70be0u } },  /* field +0x58 (read off the getter) */
  { "get_deltaTime", 0x07d69bcu, { 0xe92d4800u, 0xebee28bau, 0xe5900068u, 0xe8bd8800u } },  /* field +0x68 (read off the getter) */
  { "get_unscaledTime", 0x07d69e4u, { 0xe92d4800u, 0xebee28b0u, 0xedd00b2au, 0xeeb70be0u } },  /* field +0xa8 (read off the getter) */
  { "get_unscaledDeltaTime", 0x07d69fcu, { 0xe92d4800u, 0xebee28aau, 0xedd00b2cu, 0xeeb70be0u } },  /* field +0xb0 (read off the getter) */
  { "get_fixedDeltaTime", 0x07d6a14u, { 0xe92d4800u, 0xebee28a4u, 0xe5900028u, 0xe8bd8800u } },  /* field +0x28 (read off the getter) */
  { "set_fixedDeltaTime", 0x07d6a24u, { 0xe92d4010u, 0xe1a04000u, 0xebee289fu, 0xe1a01004u } },  /* control-flow getter */
  { "get_timeScale", 0x07d6a74u, { 0xe92d4800u, 0xebee288cu, 0xe59000bcu, 0xe8bd8800u } },  /* field +0xbc (read off the getter) */
  { "set_timeScale", 0x07d6a84u, { 0xe92d4010u, 0xe1a04000u, 0xebee2887u, 0xe1a01004u } },  /* control-flow getter */
  { "get_frameCount", 0x07d6a9cu, { 0xe92d4800u, 0xebee2882u, 0xe590007cu, 0xe8bd8800u } },  /* field +0x7c (read off the getter) */
  { "get_realtimeSinceStartup", 0x07d6abcu, { 0xe92d4800u, 0xebee287au, 0xebee27a7u, 0xec410b30u } },  /* control-flow getter */
};

/* ===== VSYNC ("swappy"): pumped, Choreographer patched to ret ===== */

/* ===== GC: Mono bdwgc tkill-based thread suspend (4 offsets) ===== */
#define DCR_MONO_THREAD_KILL       0x02bbb5cu   /* tkill wrapper */
#define DCR_MONO_GC_SUSPEND_FN         0x02bbbccu
#define DCR_MONO_GC_SUSPEND_SIG        30u
static const uint32_t DCR_GUARD_MONO_GC_SUSPEND[4] = { 0xe92d4810u, 0xe28db008u, 0xe24dd01cu, 0xe59f41b4u };
#define DCR_MONO_GC_RESTART_FN         0x02bc068u
#define DCR_MONO_GC_RESTART_SIG        24u
static const uint32_t DCR_GUARD_MONO_GC_RESTART[4] = { 0xe92d49f0u, 0xe28db018u, 0xe24dd01cu, 0xe59f61a4u };
#define DCR_MONO_GC_ACK_SEM_WAIT   0x0015cacu   /* restart ack sem_wait */

/* ===== MONO internals (libmono RVAs) ===== */
#define DCR_MONO_RVA_FlushIcache   0x010dcb0u   /* mono_arch_flush_icache: Linux cacheflush svc */
static const uint32_t DCR_MONO_GUARD_FlushIcache[4] = { 0xe92d0890u, 0xe28db008u, 0xe24dd014u, 0xe50b0018u };
#define DCR_MONO_RVA_SuspendHandler 0x02bb79cu  /* GC_suspend_handler (reference) */
static const uint32_t DCR_MONO_GUARD_SuspendHandler[4] = { 0xe92d4810u, 0xe28db008u, 0xe24dd01cu, 0xe50b0020u };
#define DCR_MONO_RVA_LookupThread  0x02ba5acu   /* GC_lookup_thread(pthread_t) */
static const uint32_t DCR_MONO_GUARD_LookupThread[4] = { 0xe92d4810u, 0xe28db008u, 0xe24dd014u, 0xe50b0018u };
#define DCR_MONO_GOT_StopCount     0x0391be0u   /* GOT slot -> &GC_stop_count */
#define DCR_MONO_GOT_AckSem        0x0391be8u   /* GOT slot -> &GC_suspend_ack_sem */
#define DCR_MONO_GCT_SIGNAL     0xc   /* GC_thread->stop_info field */
#define DCR_MONO_GCT_LAST_STOP  0x10   /* GC_thread->stop_info field */
#define DCR_MONO_GCT_STACK_PTR  0x14   /* GC_thread->stop_info field */

#endif /* DCR_OFFSETS_H */
