/* imports.c -- GENERATED by runtime/tools/gen_imports.py; do not edit.
 *
 * Every import of libmain/libunity/libmono that no loaded module
 * exports (gl* aside: the GL layer serves those), mapped to the host
 * function or object that serves it: b_* shims for the bionic ABI
 * (bionic_*.c, android_ndk.c, gl_*.c, the port's files), and newlib
 * directly where the two ABIs agree. Declared through asm labels so no
 * C prototype is needed (or can conflict): only the address is taken
 * here. The search over the table is the runtime's imports_lookup.c.
 *
 * Weak imports bound to NULL on purpose: __cxa_begin_cleanup, __cxa_call_unexpected, __cxa_type_match, __data_start, data_start.
 * MIT.
 */
#include "imports.h"

extern const char sym___errno[] __asm__("__errno");
extern const char sym_acos[] __asm__("acos");
extern const char sym_acosf[] __asm__("acosf");
extern const char sym_asin[] __asm__("asin");
extern const char sym_asinf[] __asm__("asinf");
extern const char sym_atan[] __asm__("atan");
extern const char sym_atan2[] __asm__("atan2");
extern const char sym_atan2f[] __asm__("atan2f");
extern const char sym_atanf[] __asm__("atanf");
extern const char sym_atoi[] __asm__("atoi");
extern const char sym_atol[] __asm__("atol");
extern const char sym_b_AConfiguration_delete[] __asm__("b_AConfiguration_delete");
extern const char sym_b_AConfiguration_fromAssetManager[] __asm__("b_AConfiguration_fromAssetManager");
extern const char sym_b_AConfiguration_new[] __asm__("b_AConfiguration_new");
extern const char sym_b_AInputEvent_getDeviceId[] __asm__("b_AInputEvent_getDeviceId");
extern const char sym_b_AInputEvent_getSource[] __asm__("b_AInputEvent_getSource");
extern const char sym_b_AInputEvent_getType[] __asm__("b_AInputEvent_getType");
extern const char sym_b_AInputQueue_attachLooper[] __asm__("b_AInputQueue_attachLooper");
extern const char sym_b_AInputQueue_detachLooper[] __asm__("b_AInputQueue_detachLooper");
extern const char sym_b_AInputQueue_finishEvent[] __asm__("b_AInputQueue_finishEvent");
extern const char sym_b_AInputQueue_getEvent[] __asm__("b_AInputQueue_getEvent");
extern const char sym_b_AInputQueue_preDispatchEvent[] __asm__("b_AInputQueue_preDispatchEvent");
extern const char sym_b_AKeyEvent_getAction[] __asm__("b_AKeyEvent_getAction");
extern const char sym_b_AKeyEvent_getKeyCode[] __asm__("b_AKeyEvent_getKeyCode");
extern const char sym_b_AKeyEvent_getMetaState[] __asm__("b_AKeyEvent_getMetaState");
extern const char sym_b_ALooper_forThread[] __asm__("b_ALooper_forThread");
extern const char sym_b_ALooper_pollAll[] __asm__("b_ALooper_pollAll");
extern const char sym_b_ALooper_prepare[] __asm__("b_ALooper_prepare");
extern const char sym_b_ALooper_wake[] __asm__("b_ALooper_wake");
extern const char sym_b_AMotionEvent_getAction[] __asm__("b_AMotionEvent_getAction");
extern const char sym_b_AMotionEvent_getDownTime[] __asm__("b_AMotionEvent_getDownTime");
extern const char sym_b_AMotionEvent_getEdgeFlags[] __asm__("b_AMotionEvent_getEdgeFlags");
extern const char sym_b_AMotionEvent_getEventTime[] __asm__("b_AMotionEvent_getEventTime");
extern const char sym_b_AMotionEvent_getFlags[] __asm__("b_AMotionEvent_getFlags");
extern const char sym_b_AMotionEvent_getHistoricalEventTime[] __asm__("b_AMotionEvent_getHistoricalEventTime");
extern const char sym_b_AMotionEvent_getHistoricalPressure[] __asm__("b_AMotionEvent_getHistoricalPressure");
extern const char sym_b_AMotionEvent_getHistoricalSize[] __asm__("b_AMotionEvent_getHistoricalSize");
extern const char sym_b_AMotionEvent_getHistoricalX[] __asm__("b_AMotionEvent_getHistoricalX");
extern const char sym_b_AMotionEvent_getHistoricalY[] __asm__("b_AMotionEvent_getHistoricalY");
extern const char sym_b_AMotionEvent_getHistorySize[] __asm__("b_AMotionEvent_getHistorySize");
extern const char sym_b_AMotionEvent_getMetaState[] __asm__("b_AMotionEvent_getMetaState");
extern const char sym_b_AMotionEvent_getOrientation[] __asm__("b_AMotionEvent_getOrientation");
extern const char sym_b_AMotionEvent_getPointerCount[] __asm__("b_AMotionEvent_getPointerCount");
extern const char sym_b_AMotionEvent_getPointerId[] __asm__("b_AMotionEvent_getPointerId");
extern const char sym_b_AMotionEvent_getPressure[] __asm__("b_AMotionEvent_getPressure");
extern const char sym_b_AMotionEvent_getSize[] __asm__("b_AMotionEvent_getSize");
extern const char sym_b_AMotionEvent_getToolMajor[] __asm__("b_AMotionEvent_getToolMajor");
extern const char sym_b_AMotionEvent_getToolMinor[] __asm__("b_AMotionEvent_getToolMinor");
extern const char sym_b_AMotionEvent_getTouchMajor[] __asm__("b_AMotionEvent_getTouchMajor");
extern const char sym_b_AMotionEvent_getTouchMinor[] __asm__("b_AMotionEvent_getTouchMinor");
extern const char sym_b_AMotionEvent_getX[] __asm__("b_AMotionEvent_getX");
extern const char sym_b_AMotionEvent_getXPrecision[] __asm__("b_AMotionEvent_getXPrecision");
extern const char sym_b_AMotionEvent_getY[] __asm__("b_AMotionEvent_getY");
extern const char sym_b_AMotionEvent_getYPrecision[] __asm__("b_AMotionEvent_getYPrecision");
extern const char sym_b_ANativeWindow_acquire[] __asm__("b_ANativeWindow_acquire");
extern const char sym_b_ANativeWindow_fromSurface[] __asm__("b_ANativeWindow_fromSurface");
extern const char sym_b_ANativeWindow_getHeight[] __asm__("b_ANativeWindow_getHeight");
extern const char sym_b_ANativeWindow_getWidth[] __asm__("b_ANativeWindow_getWidth");
extern const char sym_b_ANativeWindow_lock[] __asm__("b_ANativeWindow_lock");
extern const char sym_b_ANativeWindow_release[] __asm__("b_ANativeWindow_release");
extern const char sym_b_ANativeWindow_setBuffersGeometry[] __asm__("b_ANativeWindow_setBuffersGeometry");
extern const char sym_b_ANativeWindow_unlockAndPost[] __asm__("b_ANativeWindow_unlockAndPost");
extern const char sym_b_ASensorEventQueue_disableSensor[] __asm__("b_ASensorEventQueue_disableSensor");
extern const char sym_b_ASensorEventQueue_enableSensor[] __asm__("b_ASensorEventQueue_enableSensor");
extern const char sym_b_ASensorEventQueue_getEvents[] __asm__("b_ASensorEventQueue_getEvents");
extern const char sym_b_ASensorEventQueue_hasEvents[] __asm__("b_ASensorEventQueue_hasEvents");
extern const char sym_b_ASensorEventQueue_setEventRate[] __asm__("b_ASensorEventQueue_setEventRate");
extern const char sym_b_ASensorManager_createEventQueue[] __asm__("b_ASensorManager_createEventQueue");
extern const char sym_b_ASensorManager_destroyEventQueue[] __asm__("b_ASensorManager_destroyEventQueue");
extern const char sym_b_ASensorManager_getDefaultSensor[] __asm__("b_ASensorManager_getDefaultSensor");
extern const char sym_b_ASensorManager_getInstance[] __asm__("b_ASensorManager_getInstance");
extern const char sym_b_ASensorManager_getSensorList[] __asm__("b_ASensorManager_getSensorList");
extern const char sym_b_ASensor_getMinDelay[] __asm__("b_ASensor_getMinDelay");
extern const char sym_b_ASensor_getName[] __asm__("b_ASensor_getName");
extern const char sym_b_ASensor_getResolution[] __asm__("b_ASensor_getResolution");
extern const char sym_b_ASensor_getType[] __asm__("b_ASensor_getType");
extern const char sym_b_ASensor_getVendor[] __asm__("b_ASensor_getVendor");
extern const char sym_b_SHA1Final[] __asm__("b_SHA1Final");
extern const char sym_b_SHA1Init[] __asm__("b_SHA1Init");
extern const char sym_b_SHA1Update[] __asm__("b_SHA1Update");
extern const char sym_b___aeabi_atexit[] __asm__("b___aeabi_atexit");
extern const char sym_b___aeabi_memcpy[] __asm__("b___aeabi_memcpy");
extern const char sym_b___aeabi_memmove[] __asm__("b___aeabi_memmove");
extern const char sym_b___aeabi_memset[] __asm__("b___aeabi_memset");
extern const char sym_b___android_log_print[] __asm__("b___android_log_print");
extern const char sym_b___android_log_vprint[] __asm__("b___android_log_vprint");
extern const char sym_b___android_log_write[] __asm__("b___android_log_write");
extern const char sym_b___cxa_atexit[] __asm__("b___cxa_atexit");
extern const char sym_b___cxa_finalize[] __asm__("b___cxa_finalize");
extern const char sym_b___get_h_errno[] __asm__("b___get_h_errno");
extern const char sym_b___gnu_Unwind_Find_exidx[] __asm__("b___gnu_Unwind_Find_exidx");
extern const char sym_b___google_potentially_blocking_region_begin[] __asm__("b___google_potentially_blocking_region_begin");
extern const char sym_b___google_potentially_blocking_region_end[] __asm__("b___google_potentially_blocking_region_end");
extern const char sym_b___isfinitef[] __asm__("b___isfinitef");
extern const char sym_b___page_size[] __asm__("b___page_size");
extern const char sym_b___pthread_cleanup_pop[] __asm__("b___pthread_cleanup_pop");
extern const char sym_b___pthread_cleanup_push[] __asm__("b___pthread_cleanup_push");
extern const char sym_b___sF[] __asm__("b___sF");
extern const char sym_b___stack_chk_fail[] __asm__("b___stack_chk_fail");
extern const char sym_b___stack_chk_guard[] __asm__("b___stack_chk_guard");
extern const char sym_b___system_property_get[] __asm__("b___system_property_get");
extern const char sym_b__ctype_[] __asm__("b__ctype_");
extern const char sym_b__exit[] __asm__("b__exit");
extern const char sym_b__tolower_tab_[] __asm__("b__tolower_tab_");
extern const char sym_b__toupper_tab_[] __asm__("b__toupper_tab_");
extern const char sym_b_abort[] __asm__("b_abort");
extern const char sym_b_accept[] __asm__("b_accept");
extern const char sym_b_access[] __asm__("b_access");
extern const char sym_b_bind[] __asm__("b_bind");
extern const char sym_b_bsd_signal[] __asm__("b_bsd_signal");
extern const char sym_b_btowc[] __asm__("b_btowc");
extern const char sym_b_ceil[] __asm__("b_ceil");
extern const char sym_b_ceilf[] __asm__("b_ceilf");
extern const char sym_b_chdir[] __asm__("b_chdir");
extern const char sym_b_chmod[] __asm__("b_chmod");
extern const char sym_b_clearerr[] __asm__("b_clearerr");
extern const char sym_b_clock[] __asm__("b_clock");
extern const char sym_b_clock_getres[] __asm__("b_clock_getres");
extern const char sym_b_clock_gettime[] __asm__("b_clock_gettime");
extern const char sym_b_close[] __asm__("b_close");
extern const char sym_b_closedir[] __asm__("b_closedir");
extern const char sym_b_connect[] __asm__("b_connect");
extern const char sym_b_dlclose[] __asm__("b_dlclose");
extern const char sym_b_dlerror[] __asm__("b_dlerror");
extern const char sym_b_dlopen[] __asm__("b_dlopen");
extern const char sym_b_dlsym[] __asm__("b_dlsym");
extern const char sym_b_dup2[] __asm__("b_dup2");
extern const char sym_b_eglChooseConfig[] __asm__("b_eglChooseConfig");
extern const char sym_b_eglCreateContext[] __asm__("b_eglCreateContext");
extern const char sym_b_eglCreateWindowSurface[] __asm__("b_eglCreateWindowSurface");
extern const char sym_b_eglDestroyContext[] __asm__("b_eglDestroyContext");
extern const char sym_b_eglDestroySurface[] __asm__("b_eglDestroySurface");
extern const char sym_b_eglGetConfigAttrib[] __asm__("b_eglGetConfigAttrib");
extern const char sym_b_eglGetCurrentContext[] __asm__("b_eglGetCurrentContext");
extern const char sym_b_eglGetCurrentSurface[] __asm__("b_eglGetCurrentSurface");
extern const char sym_b_eglGetDisplay[] __asm__("b_eglGetDisplay");
extern const char sym_b_eglGetError[] __asm__("b_eglGetError");
extern const char sym_b_eglGetProcAddress[] __asm__("b_eglGetProcAddress");
extern const char sym_b_eglInitialize[] __asm__("b_eglInitialize");
extern const char sym_b_eglMakeCurrent[] __asm__("b_eglMakeCurrent");
extern const char sym_b_eglQueryString[] __asm__("b_eglQueryString");
extern const char sym_b_eglQuerySurface[] __asm__("b_eglQuerySurface");
extern const char sym_b_eglSwapBuffers[] __asm__("b_eglSwapBuffers");
extern const char sym_b_eglSwapInterval[] __asm__("b_eglSwapInterval");
extern const char sym_b_eglTerminate[] __asm__("b_eglTerminate");
extern const char sym_b_environ[] __asm__("b_environ");
extern const char sym_b_epoll_create[] __asm__("b_epoll_create");
extern const char sym_b_epoll_ctl[] __asm__("b_epoll_ctl");
extern const char sym_b_epoll_wait[] __asm__("b_epoll_wait");
extern const char sym_b_execl[] __asm__("b_execl");
extern const char sym_b_execv[] __asm__("b_execv");
extern const char sym_b_execve[] __asm__("b_execve");
extern const char sym_b_exit[] __asm__("b_exit");
extern const char sym_b_fabsf[] __asm__("b_fabsf");
extern const char sym_b_fclose[] __asm__("b_fclose");
extern const char sym_b_fcntl[] __asm__("b_fcntl");
extern const char sym_b_fdopen[] __asm__("b_fdopen");
extern const char sym_b_ferror[] __asm__("b_ferror");
extern const char sym_b_fflush[] __asm__("b_fflush");
extern const char sym_b_fgets[] __asm__("b_fgets");
extern const char sym_b_flock[] __asm__("b_flock");
extern const char sym_b_floor[] __asm__("b_floor");
extern const char sym_b_floorf[] __asm__("b_floorf");
extern const char sym_b_fopen[] __asm__("b_fopen");
extern const char sym_b_fork[] __asm__("b_fork");
extern const char sym_b_fprintf[] __asm__("b_fprintf");
extern const char sym_b_fputc[] __asm__("b_fputc");
extern const char sym_b_fputs[] __asm__("b_fputs");
extern const char sym_b_fread[] __asm__("b_fread");
extern const char sym_b_freeaddrinfo[] __asm__("b_freeaddrinfo");
extern const char sym_b_fscanf[] __asm__("b_fscanf");
extern const char sym_b_fseek[] __asm__("b_fseek");
extern const char sym_b_fstat[] __asm__("b_fstat");
extern const char sym_b_fsync[] __asm__("b_fsync");
extern const char sym_b_ftell[] __asm__("b_ftell");
extern const char sym_b_ftruncate[] __asm__("b_ftruncate");
extern const char sym_b_fwrite[] __asm__("b_fwrite");
extern const char sym_b_gai_strerror[] __asm__("b_gai_strerror");
extern const char sym_b_getaddrinfo[] __asm__("b_getaddrinfo");
extern const char sym_b_getc[] __asm__("b_getc");
extern const char sym_b_getcwd[] __asm__("b_getcwd");
extern const char sym_b_getdtablesize[] __asm__("b_getdtablesize");
extern const char sym_b_getenv[] __asm__("b_getenv");
extern const char sym_b_geteuid[] __asm__("b_geteuid");
extern const char sym_b_getgrgid[] __asm__("b_getgrgid");
extern const char sym_b_getgrnam[] __asm__("b_getgrnam");
extern const char sym_b_gethostbyaddr[] __asm__("b_gethostbyaddr");
extern const char sym_b_gethostbyname[] __asm__("b_gethostbyname");
extern const char sym_b_gethostname[] __asm__("b_gethostname");
extern const char sym_b_getnameinfo[] __asm__("b_getnameinfo");
extern const char sym_b_getpeername[] __asm__("b_getpeername");
extern const char sym_b_getpid[] __asm__("b_getpid");
extern const char sym_b_getpriority[] __asm__("b_getpriority");
extern const char sym_b_getpwnam[] __asm__("b_getpwnam");
extern const char sym_b_getpwuid[] __asm__("b_getpwuid");
extern const char sym_b_getresuid[] __asm__("b_getresuid");
extern const char sym_b_getrusage[] __asm__("b_getrusage");
extern const char sym_b_getsockname[] __asm__("b_getsockname");
extern const char sym_b_getsockopt[] __asm__("b_getsockopt");
extern const char sym_b_gettid[] __asm__("b_gettid");
extern const char sym_b_gettimeofday[] __asm__("b_gettimeofday");
extern const char sym_b_getuid[] __asm__("b_getuid");
extern const char sym_b_getwc[] __asm__("b_getwc");
extern const char sym_b_gmtime[] __asm__("b_gmtime");
extern const char sym_b_inet_addr[] __asm__("b_inet_addr");
extern const char sym_b_inet_aton[] __asm__("b_inet_aton");
extern const char sym_b_inet_ntoa[] __asm__("b_inet_ntoa");
extern const char sym_b_inet_ntop[] __asm__("b_inet_ntop");
extern const char sym_b_inet_pton[] __asm__("b_inet_pton");
extern const char sym_b_ioctl[] __asm__("b_ioctl");
extern const char sym_b_isatty[] __asm__("b_isatty");
extern const char sym_b_isnan[] __asm__("b_isnan");
extern const char sym_b_kill[] __asm__("b_kill");
extern const char sym_b_listen[] __asm__("b_listen");
extern const char sym_b_localtime[] __asm__("b_localtime");
extern const char sym_b_longjmp[] __asm__("b_longjmp");
extern const char sym_b_lseek[] __asm__("b_lseek");
extern const char sym_b_lstat[] __asm__("b_lstat");
extern const char sym_b_madvise[] __asm__("b_madvise");
extern const char sym_b_mbrtowc[] __asm__("b_mbrtowc");
extern const char sym_b_memcpy[] __asm__("b_memcpy");
extern const char sym_b_memmove[] __asm__("b_memmove");
extern const char sym_b_memset[] __asm__("b_memset");
extern const char sym_b_mkdir[] __asm__("b_mkdir");
extern const char sym_b_mkstemp[] __asm__("b_mkstemp");
extern const char sym_b_mktime[] __asm__("b_mktime");
extern const char sym_b_mmap[] __asm__("b_mmap");
extern const char sym_b_modf[] __asm__("b_modf");
extern const char sym_b_modff[] __asm__("b_modff");
extern const char sym_b_mprotect[] __asm__("b_mprotect");
extern const char sym_b_mremap[] __asm__("b_mremap");
extern const char sym_b_munmap[] __asm__("b_munmap");
extern const char sym_b_nanosleep[] __asm__("b_nanosleep");
extern const char sym_b_open[] __asm__("b_open");
extern const char sym_b_opendir[] __asm__("b_opendir");
extern const char sym_b_pclose[] __asm__("b_pclose");
extern const char sym_b_perror[] __asm__("b_perror");
extern const char sym_b_pipe[] __asm__("b_pipe");
extern const char sym_b_poll[] __asm__("b_poll");
extern const char sym_b_popen[] __asm__("b_popen");
extern const char sym_b_prctl[] __asm__("b_prctl");
extern const char sym_b_printf[] __asm__("b_printf");
extern const char sym_b_pthread_attr_destroy[] __asm__("b_pthread_attr_destroy");
extern const char sym_b_pthread_attr_getdetachstate[] __asm__("b_pthread_attr_getdetachstate");
extern const char sym_b_pthread_attr_getstack[] __asm__("b_pthread_attr_getstack");
extern const char sym_b_pthread_attr_init[] __asm__("b_pthread_attr_init");
extern const char sym_b_pthread_attr_setdetachstate[] __asm__("b_pthread_attr_setdetachstate");
extern const char sym_b_pthread_attr_setschedparam[] __asm__("b_pthread_attr_setschedparam");
extern const char sym_b_pthread_attr_setschedpolicy[] __asm__("b_pthread_attr_setschedpolicy");
extern const char sym_b_pthread_attr_setstacksize[] __asm__("b_pthread_attr_setstacksize");
extern const char sym_b_pthread_cond_broadcast[] __asm__("b_pthread_cond_broadcast");
extern const char sym_b_pthread_cond_destroy[] __asm__("b_pthread_cond_destroy");
extern const char sym_b_pthread_cond_init[] __asm__("b_pthread_cond_init");
extern const char sym_b_pthread_cond_signal[] __asm__("b_pthread_cond_signal");
extern const char sym_b_pthread_cond_timedwait[] __asm__("b_pthread_cond_timedwait");
extern const char sym_b_pthread_cond_timedwait_monotonic_np[] __asm__("b_pthread_cond_timedwait_monotonic_np");
extern const char sym_b_pthread_cond_wait[] __asm__("b_pthread_cond_wait");
extern const char sym_b_pthread_create[] __asm__("b_pthread_create");
extern const char sym_b_pthread_detach[] __asm__("b_pthread_detach");
extern const char sym_b_pthread_equal[] __asm__("b_pthread_equal");
extern const char sym_b_pthread_exit[] __asm__("b_pthread_exit");
extern const char sym_b_pthread_getattr_np[] __asm__("b_pthread_getattr_np");
extern const char sym_b_pthread_getschedparam[] __asm__("b_pthread_getschedparam");
extern const char sym_b_pthread_getspecific[] __asm__("b_pthread_getspecific");
extern const char sym_b_pthread_join[] __asm__("b_pthread_join");
extern const char sym_b_pthread_key_create[] __asm__("b_pthread_key_create");
extern const char sym_b_pthread_key_delete[] __asm__("b_pthread_key_delete");
extern const char sym_b_pthread_kill[] __asm__("b_pthread_kill");
extern const char sym_b_pthread_mutex_destroy[] __asm__("b_pthread_mutex_destroy");
extern const char sym_b_pthread_mutex_init[] __asm__("b_pthread_mutex_init");
extern const char sym_b_pthread_mutex_lock[] __asm__("b_pthread_mutex_lock");
extern const char sym_b_pthread_mutex_trylock[] __asm__("b_pthread_mutex_trylock");
extern const char sym_b_pthread_mutex_unlock[] __asm__("b_pthread_mutex_unlock");
extern const char sym_b_pthread_mutexattr_destroy[] __asm__("b_pthread_mutexattr_destroy");
extern const char sym_b_pthread_mutexattr_init[] __asm__("b_pthread_mutexattr_init");
extern const char sym_b_pthread_mutexattr_settype[] __asm__("b_pthread_mutexattr_settype");
extern const char sym_b_pthread_once[] __asm__("b_pthread_once");
extern const char sym_b_pthread_self[] __asm__("b_pthread_self");
extern const char sym_b_pthread_setname_np[] __asm__("b_pthread_setname_np");
extern const char sym_b_pthread_setschedparam[] __asm__("b_pthread_setschedparam");
extern const char sym_b_pthread_setspecific[] __asm__("b_pthread_setspecific");
extern const char sym_b_pthread_sigmask[] __asm__("b_pthread_sigmask");
extern const char sym_b_ptrace[] __asm__("b_ptrace");
extern const char sym_b_putc[] __asm__("b_putc");
extern const char sym_b_putchar[] __asm__("b_putchar");
extern const char sym_b_puts[] __asm__("b_puts");
extern const char sym_b_putwc[] __asm__("b_putwc");
extern const char sym_b_raise[] __asm__("b_raise");
extern const char sym_b_read[] __asm__("b_read");
extern const char sym_b_readdir[] __asm__("b_readdir");
extern const char sym_b_readlink[] __asm__("b_readlink");
extern const char sym_b_recv[] __asm__("b_recv");
extern const char sym_b_recvfrom[] __asm__("b_recvfrom");
extern const char sym_b_recvmsg[] __asm__("b_recvmsg");
extern const char sym_b_rename[] __asm__("b_rename");
extern const char sym_b_rint[] __asm__("b_rint");
extern const char sym_b_rmdir[] __asm__("b_rmdir");
extern const char sym_b_round[] __asm__("b_round");
extern const char sym_b_roundf[] __asm__("b_roundf");
extern const char sym_b_sched_get_priority_max[] __asm__("b_sched_get_priority_max");
extern const char sym_b_sched_get_priority_min[] __asm__("b_sched_get_priority_min");
extern const char sym_b_sched_yield[] __asm__("b_sched_yield");
extern const char sym_b_select[] __asm__("b_select");
extern const char sym_b_sem_destroy[] __asm__("b_sem_destroy");
extern const char sym_b_sem_getvalue[] __asm__("b_sem_getvalue");
extern const char sym_b_sem_init[] __asm__("b_sem_init");
extern const char sym_b_sem_post[] __asm__("b_sem_post");
extern const char sym_b_sem_timedwait[] __asm__("b_sem_timedwait");
extern const char sym_b_sem_trywait[] __asm__("b_sem_trywait");
extern const char sym_b_sem_wait[] __asm__("b_sem_wait");
extern const char sym_b_send[] __asm__("b_send");
extern const char sym_b_sendfile[] __asm__("b_sendfile");
extern const char sym_b_sendmsg[] __asm__("b_sendmsg");
extern const char sym_b_sendto[] __asm__("b_sendto");
extern const char sym_b_setenv[] __asm__("b_setenv");
extern const char sym_b_setitimer[] __asm__("b_setitimer");
extern const char sym_b_setjmp[] __asm__("b_setjmp");
extern const char sym_b_setlocale[] __asm__("b_setlocale");
extern const char sym_b_setpriority[] __asm__("b_setpriority");
extern const char sym_b_setresuid[] __asm__("b_setresuid");
extern const char sym_b_setsockopt[] __asm__("b_setsockopt");
extern const char sym_b_setvbuf[] __asm__("b_setvbuf");
extern const char sym_b_shutdown[] __asm__("b_shutdown");
extern const char sym_b_sigaction[] __asm__("b_sigaction");
extern const char sym_b_siglongjmp[] __asm__("b_siglongjmp");
extern const char sym_b_sigprocmask[] __asm__("b_sigprocmask");
extern const char sym_b_sigsetjmp[] __asm__("b_sigsetjmp");
extern const char sym_b_sigsuspend[] __asm__("b_sigsuspend");
extern const char sym_b_sleep[] __asm__("b_sleep");
extern const char sym_b_snprintf[] __asm__("b_snprintf");
extern const char sym_b_socket[] __asm__("b_socket");
extern const char sym_b_sprintf[] __asm__("b_sprintf");
extern const char sym_b_sqrt[] __asm__("b_sqrt");
extern const char sym_b_sqrtf[] __asm__("b_sqrtf");
extern const char sym_b_stat[] __asm__("b_stat");
extern const char sym_b_strerror[] __asm__("b_strerror");
extern const char sym_b_strftime[] __asm__("b_strftime");
extern const char sym_b_syscall[] __asm__("b_syscall");
extern const char sym_b_sysconf[] __asm__("b_sysconf");
extern const char sym_b_system[] __asm__("b_system");
extern const char sym_b_time[] __asm__("b_time");
extern const char sym_b_tkill[] __asm__("b_tkill");
extern const char sym_b_trunc[] __asm__("b_trunc");
extern const char sym_b_truncate[] __asm__("b_truncate");
extern const char sym_b_truncf[] __asm__("b_truncf");
extern const char sym_b_uname[] __asm__("b_uname");
extern const char sym_b_ungetc[] __asm__("b_ungetc");
extern const char sym_b_ungetwc[] __asm__("b_ungetwc");
extern const char sym_b_unlink[] __asm__("b_unlink");
extern const char sym_b_unsetenv[] __asm__("b_unsetenv");
extern const char sym_b_usleep[] __asm__("b_usleep");
extern const char sym_b_utime[] __asm__("b_utime");
extern const char sym_b_vasprintf[] __asm__("b_vasprintf");
extern const char sym_b_vfprintf[] __asm__("b_vfprintf");
extern const char sym_b_vprintf[] __asm__("b_vprintf");
extern const char sym_b_vsnprintf[] __asm__("b_vsnprintf");
extern const char sym_b_vsprintf[] __asm__("b_vsprintf");
extern const char sym_b_waitpid[] __asm__("b_waitpid");
extern const char sym_b_wcrtomb[] __asm__("b_wcrtomb");
extern const char sym_b_wcsftime[] __asm__("b_wcsftime");
extern const char sym_b_wctob[] __asm__("b_wctob");
extern const char sym_b_wprintf[] __asm__("b_wprintf");
extern const char sym_b_write[] __asm__("b_write");
extern const char sym_b_writev[] __asm__("b_writev");
extern const char sym_bsearch[] __asm__("bsearch");
extern const char sym_calloc[] __asm__("calloc");
extern const char sym_cos[] __asm__("cos");
extern const char sym_cosf[] __asm__("cosf");
extern const char sym_cosh[] __asm__("cosh");
extern const char sym_div[] __asm__("div");
extern const char sym_exp[] __asm__("exp");
extern const char sym_exp2f[] __asm__("exp2f");
extern const char sym_expf[] __asm__("expf");
extern const char sym_fmod[] __asm__("fmod");
extern const char sym_fmodf[] __asm__("fmodf");
extern const char sym_free[] __asm__("free");
extern const char sym_frexp[] __asm__("frexp");
extern const char sym_isalnum[] __asm__("isalnum");
extern const char sym_isalpha[] __asm__("isalpha");
extern const char sym_isspace[] __asm__("isspace");
extern const char sym_iswctype[] __asm__("iswctype");
extern const char sym_isxdigit[] __asm__("isxdigit");
extern const char sym_ldexp[] __asm__("ldexp");
extern const char sym_log[] __asm__("log");
extern const char sym_log10[] __asm__("log10");
extern const char sym_log10f[] __asm__("log10f");
extern const char sym_logf[] __asm__("logf");
extern const char sym_lrand48[] __asm__("lrand48");
extern const char sym_malloc[] __asm__("malloc");
extern const char sym_memalign[] __asm__("memalign");
extern const char sym_memchr[] __asm__("memchr");
extern const char sym_memcmp[] __asm__("memcmp");
extern const char sym_memmem[] __asm__("memmem");
extern const char sym_pow[] __asm__("pow");
extern const char sym_powf[] __asm__("powf");
extern const char sym_qsort[] __asm__("qsort");
extern const char sym_realloc[] __asm__("realloc");
extern const char sym_sin[] __asm__("sin");
extern const char sym_sinf[] __asm__("sinf");
extern const char sym_sinh[] __asm__("sinh");
extern const char sym_srand48[] __asm__("srand48");
extern const char sym_sscanf[] __asm__("sscanf");
extern const char sym_strcasecmp[] __asm__("strcasecmp");
extern const char sym_strcasestr[] __asm__("strcasestr");
extern const char sym_strcat[] __asm__("strcat");
extern const char sym_strchr[] __asm__("strchr");
extern const char sym_strcmp[] __asm__("strcmp");
extern const char sym_strcoll[] __asm__("strcoll");
extern const char sym_strcpy[] __asm__("strcpy");
extern const char sym_strdup[] __asm__("strdup");
extern const char sym_strlcpy[] __asm__("strlcpy");
extern const char sym_strlen[] __asm__("strlen");
extern const char sym_strncasecmp[] __asm__("strncasecmp");
extern const char sym_strncat[] __asm__("strncat");
extern const char sym_strncmp[] __asm__("strncmp");
extern const char sym_strncpy[] __asm__("strncpy");
extern const char sym_strpbrk[] __asm__("strpbrk");
extern const char sym_strrchr[] __asm__("strrchr");
extern const char sym_strsep[] __asm__("strsep");
extern const char sym_strstr[] __asm__("strstr");
extern const char sym_strtod[] __asm__("strtod");
extern const char sym_strtok[] __asm__("strtok");
extern const char sym_strtok_r[] __asm__("strtok_r");
extern const char sym_strtol[] __asm__("strtol");
extern const char sym_strtoul[] __asm__("strtoul");
extern const char sym_strtoull[] __asm__("strtoull");
extern const char sym_strxfrm[] __asm__("strxfrm");
extern const char sym_swscanf[] __asm__("swscanf");
extern const char sym_tan[] __asm__("tan");
extern const char sym_tanf[] __asm__("tanf");
extern const char sym_tanh[] __asm__("tanh");
extern const char sym_tolower[] __asm__("tolower");
extern const char sym_towlower[] __asm__("towlower");
extern const char sym_towupper[] __asm__("towupper");
extern const char sym_wcscat[] __asm__("wcscat");
extern const char sym_wcscmp[] __asm__("wcscmp");
extern const char sym_wcscoll[] __asm__("wcscoll");
extern const char sym_wcscpy[] __asm__("wcscpy");
extern const char sym_wcslen[] __asm__("wcslen");
extern const char sym_wcsncat[] __asm__("wcsncat");
extern const char sym_wcsncmp[] __asm__("wcsncmp");
extern const char sym_wcsncpy[] __asm__("wcsncpy");
extern const char sym_wcstod[] __asm__("wcstod");
extern const char sym_wcstol[] __asm__("wcstol");
extern const char sym_wcsxfrm[] __asm__("wcsxfrm");
extern const char sym_wctype[] __asm__("wctype");
extern const char sym_wmemchr[] __asm__("wmemchr");
extern const char sym_wmemcmp[] __asm__("wmemcmp");
extern const char sym_wmemcpy[] __asm__("wmemcpy");
extern const char sym_wmemmove[] __asm__("wmemmove");
extern const char sym_wmemset[] __asm__("wmemset");

DynLibFunction dcr_imports[] = {
    {"AConfiguration_delete", (uintptr_t)sym_b_AConfiguration_delete},
    {"AConfiguration_fromAssetManager", (uintptr_t)sym_b_AConfiguration_fromAssetManager},
    {"AConfiguration_new", (uintptr_t)sym_b_AConfiguration_new},
    {"AInputEvent_getDeviceId", (uintptr_t)sym_b_AInputEvent_getDeviceId},
    {"AInputEvent_getSource", (uintptr_t)sym_b_AInputEvent_getSource},
    {"AInputEvent_getType", (uintptr_t)sym_b_AInputEvent_getType},
    {"AInputQueue_attachLooper", (uintptr_t)sym_b_AInputQueue_attachLooper},
    {"AInputQueue_detachLooper", (uintptr_t)sym_b_AInputQueue_detachLooper},
    {"AInputQueue_finishEvent", (uintptr_t)sym_b_AInputQueue_finishEvent},
    {"AInputQueue_getEvent", (uintptr_t)sym_b_AInputQueue_getEvent},
    {"AInputQueue_preDispatchEvent", (uintptr_t)sym_b_AInputQueue_preDispatchEvent},
    {"AKeyEvent_getAction", (uintptr_t)sym_b_AKeyEvent_getAction},
    {"AKeyEvent_getKeyCode", (uintptr_t)sym_b_AKeyEvent_getKeyCode},
    {"AKeyEvent_getMetaState", (uintptr_t)sym_b_AKeyEvent_getMetaState},
    {"ALooper_forThread", (uintptr_t)sym_b_ALooper_forThread},
    {"ALooper_pollAll", (uintptr_t)sym_b_ALooper_pollAll},
    {"ALooper_prepare", (uintptr_t)sym_b_ALooper_prepare},
    {"ALooper_wake", (uintptr_t)sym_b_ALooper_wake},
    {"AMotionEvent_getAction", (uintptr_t)sym_b_AMotionEvent_getAction},
    {"AMotionEvent_getDownTime", (uintptr_t)sym_b_AMotionEvent_getDownTime},
    {"AMotionEvent_getEdgeFlags", (uintptr_t)sym_b_AMotionEvent_getEdgeFlags},
    {"AMotionEvent_getEventTime", (uintptr_t)sym_b_AMotionEvent_getEventTime},
    {"AMotionEvent_getFlags", (uintptr_t)sym_b_AMotionEvent_getFlags},
    {"AMotionEvent_getHistoricalEventTime", (uintptr_t)sym_b_AMotionEvent_getHistoricalEventTime},
    {"AMotionEvent_getHistoricalPressure", (uintptr_t)sym_b_AMotionEvent_getHistoricalPressure},
    {"AMotionEvent_getHistoricalSize", (uintptr_t)sym_b_AMotionEvent_getHistoricalSize},
    {"AMotionEvent_getHistoricalX", (uintptr_t)sym_b_AMotionEvent_getHistoricalX},
    {"AMotionEvent_getHistoricalY", (uintptr_t)sym_b_AMotionEvent_getHistoricalY},
    {"AMotionEvent_getHistorySize", (uintptr_t)sym_b_AMotionEvent_getHistorySize},
    {"AMotionEvent_getMetaState", (uintptr_t)sym_b_AMotionEvent_getMetaState},
    {"AMotionEvent_getOrientation", (uintptr_t)sym_b_AMotionEvent_getOrientation},
    {"AMotionEvent_getPointerCount", (uintptr_t)sym_b_AMotionEvent_getPointerCount},
    {"AMotionEvent_getPointerId", (uintptr_t)sym_b_AMotionEvent_getPointerId},
    {"AMotionEvent_getPressure", (uintptr_t)sym_b_AMotionEvent_getPressure},
    {"AMotionEvent_getSize", (uintptr_t)sym_b_AMotionEvent_getSize},
    {"AMotionEvent_getToolMajor", (uintptr_t)sym_b_AMotionEvent_getToolMajor},
    {"AMotionEvent_getToolMinor", (uintptr_t)sym_b_AMotionEvent_getToolMinor},
    {"AMotionEvent_getTouchMajor", (uintptr_t)sym_b_AMotionEvent_getTouchMajor},
    {"AMotionEvent_getTouchMinor", (uintptr_t)sym_b_AMotionEvent_getTouchMinor},
    {"AMotionEvent_getX", (uintptr_t)sym_b_AMotionEvent_getX},
    {"AMotionEvent_getXPrecision", (uintptr_t)sym_b_AMotionEvent_getXPrecision},
    {"AMotionEvent_getY", (uintptr_t)sym_b_AMotionEvent_getY},
    {"AMotionEvent_getYPrecision", (uintptr_t)sym_b_AMotionEvent_getYPrecision},
    {"ANativeWindow_acquire", (uintptr_t)sym_b_ANativeWindow_acquire},
    {"ANativeWindow_fromSurface", (uintptr_t)sym_b_ANativeWindow_fromSurface},
    {"ANativeWindow_getHeight", (uintptr_t)sym_b_ANativeWindow_getHeight},
    {"ANativeWindow_getWidth", (uintptr_t)sym_b_ANativeWindow_getWidth},
    {"ANativeWindow_lock", (uintptr_t)sym_b_ANativeWindow_lock},
    {"ANativeWindow_release", (uintptr_t)sym_b_ANativeWindow_release},
    {"ANativeWindow_setBuffersGeometry", (uintptr_t)sym_b_ANativeWindow_setBuffersGeometry},
    {"ANativeWindow_unlockAndPost", (uintptr_t)sym_b_ANativeWindow_unlockAndPost},
    {"ASensorEventQueue_disableSensor", (uintptr_t)sym_b_ASensorEventQueue_disableSensor},
    {"ASensorEventQueue_enableSensor", (uintptr_t)sym_b_ASensorEventQueue_enableSensor},
    {"ASensorEventQueue_getEvents", (uintptr_t)sym_b_ASensorEventQueue_getEvents},
    {"ASensorEventQueue_hasEvents", (uintptr_t)sym_b_ASensorEventQueue_hasEvents},
    {"ASensorEventQueue_setEventRate", (uintptr_t)sym_b_ASensorEventQueue_setEventRate},
    {"ASensorManager_createEventQueue", (uintptr_t)sym_b_ASensorManager_createEventQueue},
    {"ASensorManager_destroyEventQueue", (uintptr_t)sym_b_ASensorManager_destroyEventQueue},
    {"ASensorManager_getDefaultSensor", (uintptr_t)sym_b_ASensorManager_getDefaultSensor},
    {"ASensorManager_getInstance", (uintptr_t)sym_b_ASensorManager_getInstance},
    {"ASensorManager_getSensorList", (uintptr_t)sym_b_ASensorManager_getSensorList},
    {"ASensor_getMinDelay", (uintptr_t)sym_b_ASensor_getMinDelay},
    {"ASensor_getName", (uintptr_t)sym_b_ASensor_getName},
    {"ASensor_getResolution", (uintptr_t)sym_b_ASensor_getResolution},
    {"ASensor_getType", (uintptr_t)sym_b_ASensor_getType},
    {"ASensor_getVendor", (uintptr_t)sym_b_ASensor_getVendor},
    {"SHA1Final", (uintptr_t)sym_b_SHA1Final},
    {"SHA1Init", (uintptr_t)sym_b_SHA1Init},
    {"SHA1Update", (uintptr_t)sym_b_SHA1Update},
    {"__aeabi_atexit", (uintptr_t)sym_b___aeabi_atexit},
    {"__aeabi_memcpy", (uintptr_t)sym_b___aeabi_memcpy},
    {"__aeabi_memmove", (uintptr_t)sym_b___aeabi_memmove},
    {"__aeabi_memset", (uintptr_t)sym_b___aeabi_memset},
    {"__android_log_print", (uintptr_t)sym_b___android_log_print},
    {"__android_log_vprint", (uintptr_t)sym_b___android_log_vprint},
    {"__android_log_write", (uintptr_t)sym_b___android_log_write},
    {"__cxa_atexit", (uintptr_t)sym_b___cxa_atexit},
    {"__cxa_finalize", (uintptr_t)sym_b___cxa_finalize},
    {"__errno", (uintptr_t)sym___errno},
    {"__get_h_errno", (uintptr_t)sym_b___get_h_errno},
    {"__gnu_Unwind_Find_exidx", (uintptr_t)sym_b___gnu_Unwind_Find_exidx},
    {"__google_potentially_blocking_region_begin", (uintptr_t)sym_b___google_potentially_blocking_region_begin},
    {"__google_potentially_blocking_region_end", (uintptr_t)sym_b___google_potentially_blocking_region_end},
    {"__isfinitef", (uintptr_t)sym_b___isfinitef},
    {"__page_size", (uintptr_t)sym_b___page_size},
    {"__pthread_cleanup_pop", (uintptr_t)sym_b___pthread_cleanup_pop},
    {"__pthread_cleanup_push", (uintptr_t)sym_b___pthread_cleanup_push},
    {"__sF", (uintptr_t)sym_b___sF},
    {"__stack_chk_fail", (uintptr_t)sym_b___stack_chk_fail},
    {"__stack_chk_guard", (uintptr_t)sym_b___stack_chk_guard},
    {"__system_property_get", (uintptr_t)sym_b___system_property_get},
    {"_ctype_", (uintptr_t)sym_b__ctype_},
    {"_exit", (uintptr_t)sym_b__exit},
    {"_tolower_tab_", (uintptr_t)sym_b__tolower_tab_},
    {"_toupper_tab_", (uintptr_t)sym_b__toupper_tab_},
    {"abort", (uintptr_t)sym_b_abort},
    {"accept", (uintptr_t)sym_b_accept},
    {"access", (uintptr_t)sym_b_access},
    {"acos", (uintptr_t)sym_acos},
    {"acosf", (uintptr_t)sym_acosf},
    {"asin", (uintptr_t)sym_asin},
    {"asinf", (uintptr_t)sym_asinf},
    {"atan", (uintptr_t)sym_atan},
    {"atan2", (uintptr_t)sym_atan2},
    {"atan2f", (uintptr_t)sym_atan2f},
    {"atanf", (uintptr_t)sym_atanf},
    {"atoi", (uintptr_t)sym_atoi},
    {"atol", (uintptr_t)sym_atol},
    {"bind", (uintptr_t)sym_b_bind},
    {"bsd_signal", (uintptr_t)sym_b_bsd_signal},
    {"bsearch", (uintptr_t)sym_bsearch},
    {"btowc", (uintptr_t)sym_b_btowc},
    {"calloc", (uintptr_t)sym_calloc},
    {"ceil", (uintptr_t)sym_b_ceil},
    {"ceilf", (uintptr_t)sym_b_ceilf},
    {"chdir", (uintptr_t)sym_b_chdir},
    {"chmod", (uintptr_t)sym_b_chmod},
    {"clearerr", (uintptr_t)sym_b_clearerr},
    {"clock", (uintptr_t)sym_b_clock},
    {"clock_getres", (uintptr_t)sym_b_clock_getres},
    {"clock_gettime", (uintptr_t)sym_b_clock_gettime},
    {"close", (uintptr_t)sym_b_close},
    {"closedir", (uintptr_t)sym_b_closedir},
    {"connect", (uintptr_t)sym_b_connect},
    {"cos", (uintptr_t)sym_cos},
    {"cosf", (uintptr_t)sym_cosf},
    {"cosh", (uintptr_t)sym_cosh},
    {"div", (uintptr_t)sym_div},
    {"dlclose", (uintptr_t)sym_b_dlclose},
    {"dlerror", (uintptr_t)sym_b_dlerror},
    {"dlopen", (uintptr_t)sym_b_dlopen},
    {"dlsym", (uintptr_t)sym_b_dlsym},
    {"dup2", (uintptr_t)sym_b_dup2},
    {"eglChooseConfig", (uintptr_t)sym_b_eglChooseConfig},
    {"eglCreateContext", (uintptr_t)sym_b_eglCreateContext},
    {"eglCreateWindowSurface", (uintptr_t)sym_b_eglCreateWindowSurface},
    {"eglDestroyContext", (uintptr_t)sym_b_eglDestroyContext},
    {"eglDestroySurface", (uintptr_t)sym_b_eglDestroySurface},
    {"eglGetConfigAttrib", (uintptr_t)sym_b_eglGetConfigAttrib},
    {"eglGetCurrentContext", (uintptr_t)sym_b_eglGetCurrentContext},
    {"eglGetCurrentSurface", (uintptr_t)sym_b_eglGetCurrentSurface},
    {"eglGetDisplay", (uintptr_t)sym_b_eglGetDisplay},
    {"eglGetError", (uintptr_t)sym_b_eglGetError},
    {"eglGetProcAddress", (uintptr_t)sym_b_eglGetProcAddress},
    {"eglInitialize", (uintptr_t)sym_b_eglInitialize},
    {"eglMakeCurrent", (uintptr_t)sym_b_eglMakeCurrent},
    {"eglQueryString", (uintptr_t)sym_b_eglQueryString},
    {"eglQuerySurface", (uintptr_t)sym_b_eglQuerySurface},
    {"eglSwapBuffers", (uintptr_t)sym_b_eglSwapBuffers},
    {"eglSwapInterval", (uintptr_t)sym_b_eglSwapInterval},
    {"eglTerminate", (uintptr_t)sym_b_eglTerminate},
    {"environ", (uintptr_t)sym_b_environ},
    {"epoll_create", (uintptr_t)sym_b_epoll_create},
    {"epoll_ctl", (uintptr_t)sym_b_epoll_ctl},
    {"epoll_wait", (uintptr_t)sym_b_epoll_wait},
    {"execl", (uintptr_t)sym_b_execl},
    {"execv", (uintptr_t)sym_b_execv},
    {"execve", (uintptr_t)sym_b_execve},
    {"exit", (uintptr_t)sym_b_exit},
    {"exp", (uintptr_t)sym_exp},
    {"exp2f", (uintptr_t)sym_exp2f},
    {"expf", (uintptr_t)sym_expf},
    {"fabsf", (uintptr_t)sym_b_fabsf},
    {"fclose", (uintptr_t)sym_b_fclose},
    {"fcntl", (uintptr_t)sym_b_fcntl},
    {"fdopen", (uintptr_t)sym_b_fdopen},
    {"ferror", (uintptr_t)sym_b_ferror},
    {"fflush", (uintptr_t)sym_b_fflush},
    {"fgets", (uintptr_t)sym_b_fgets},
    {"flock", (uintptr_t)sym_b_flock},
    {"floor", (uintptr_t)sym_b_floor},
    {"floorf", (uintptr_t)sym_b_floorf},
    {"fmod", (uintptr_t)sym_fmod},
    {"fmodf", (uintptr_t)sym_fmodf},
    {"fopen", (uintptr_t)sym_b_fopen},
    {"fork", (uintptr_t)sym_b_fork},
    {"fprintf", (uintptr_t)sym_b_fprintf},
    {"fputc", (uintptr_t)sym_b_fputc},
    {"fputs", (uintptr_t)sym_b_fputs},
    {"fread", (uintptr_t)sym_b_fread},
    {"free", (uintptr_t)sym_free},
    {"freeaddrinfo", (uintptr_t)sym_b_freeaddrinfo},
    {"frexp", (uintptr_t)sym_frexp},
    {"fscanf", (uintptr_t)sym_b_fscanf},
    {"fseek", (uintptr_t)sym_b_fseek},
    {"fstat", (uintptr_t)sym_b_fstat},
    {"fsync", (uintptr_t)sym_b_fsync},
    {"ftell", (uintptr_t)sym_b_ftell},
    {"ftruncate", (uintptr_t)sym_b_ftruncate},
    {"fwrite", (uintptr_t)sym_b_fwrite},
    {"gai_strerror", (uintptr_t)sym_b_gai_strerror},
    {"getaddrinfo", (uintptr_t)sym_b_getaddrinfo},
    {"getc", (uintptr_t)sym_b_getc},
    {"getcwd", (uintptr_t)sym_b_getcwd},
    {"getdtablesize", (uintptr_t)sym_b_getdtablesize},
    {"getenv", (uintptr_t)sym_b_getenv},
    {"geteuid", (uintptr_t)sym_b_geteuid},
    {"getgrgid", (uintptr_t)sym_b_getgrgid},
    {"getgrnam", (uintptr_t)sym_b_getgrnam},
    {"gethostbyaddr", (uintptr_t)sym_b_gethostbyaddr},
    {"gethostbyname", (uintptr_t)sym_b_gethostbyname},
    {"gethostname", (uintptr_t)sym_b_gethostname},
    {"getnameinfo", (uintptr_t)sym_b_getnameinfo},
    {"getpeername", (uintptr_t)sym_b_getpeername},
    {"getpid", (uintptr_t)sym_b_getpid},
    {"getpriority", (uintptr_t)sym_b_getpriority},
    {"getpwnam", (uintptr_t)sym_b_getpwnam},
    {"getpwuid", (uintptr_t)sym_b_getpwuid},
    {"getresuid", (uintptr_t)sym_b_getresuid},
    {"getrusage", (uintptr_t)sym_b_getrusage},
    {"getsockname", (uintptr_t)sym_b_getsockname},
    {"getsockopt", (uintptr_t)sym_b_getsockopt},
    {"gettid", (uintptr_t)sym_b_gettid},
    {"gettimeofday", (uintptr_t)sym_b_gettimeofday},
    {"getuid", (uintptr_t)sym_b_getuid},
    {"getwc", (uintptr_t)sym_b_getwc},
    {"gmtime", (uintptr_t)sym_b_gmtime},
    {"inet_addr", (uintptr_t)sym_b_inet_addr},
    {"inet_aton", (uintptr_t)sym_b_inet_aton},
    {"inet_ntoa", (uintptr_t)sym_b_inet_ntoa},
    {"inet_ntop", (uintptr_t)sym_b_inet_ntop},
    {"inet_pton", (uintptr_t)sym_b_inet_pton},
    {"ioctl", (uintptr_t)sym_b_ioctl},
    {"isalnum", (uintptr_t)sym_isalnum},
    {"isalpha", (uintptr_t)sym_isalpha},
    {"isatty", (uintptr_t)sym_b_isatty},
    {"isnan", (uintptr_t)sym_b_isnan},
    {"isspace", (uintptr_t)sym_isspace},
    {"iswctype", (uintptr_t)sym_iswctype},
    {"isxdigit", (uintptr_t)sym_isxdigit},
    {"kill", (uintptr_t)sym_b_kill},
    {"ldexp", (uintptr_t)sym_ldexp},
    {"listen", (uintptr_t)sym_b_listen},
    {"localtime", (uintptr_t)sym_b_localtime},
    {"log", (uintptr_t)sym_log},
    {"log10", (uintptr_t)sym_log10},
    {"log10f", (uintptr_t)sym_log10f},
    {"logf", (uintptr_t)sym_logf},
    {"longjmp", (uintptr_t)sym_b_longjmp},
    {"lrand48", (uintptr_t)sym_lrand48},
    {"lseek", (uintptr_t)sym_b_lseek},
    {"lstat", (uintptr_t)sym_b_lstat},
    {"madvise", (uintptr_t)sym_b_madvise},
    {"malloc", (uintptr_t)sym_malloc},
    {"mbrtowc", (uintptr_t)sym_b_mbrtowc},
    {"memalign", (uintptr_t)sym_memalign},
    {"memchr", (uintptr_t)sym_memchr},
    {"memcmp", (uintptr_t)sym_memcmp},
    {"memcpy", (uintptr_t)sym_b_memcpy},
    {"memmem", (uintptr_t)sym_memmem},
    {"memmove", (uintptr_t)sym_b_memmove},
    {"memset", (uintptr_t)sym_b_memset},
    {"mkdir", (uintptr_t)sym_b_mkdir},
    {"mkstemp", (uintptr_t)sym_b_mkstemp},
    {"mktime", (uintptr_t)sym_b_mktime},
    {"mmap", (uintptr_t)sym_b_mmap},
    {"modf", (uintptr_t)sym_b_modf},
    {"modff", (uintptr_t)sym_b_modff},
    {"mprotect", (uintptr_t)sym_b_mprotect},
    {"mremap", (uintptr_t)sym_b_mremap},
    {"munmap", (uintptr_t)sym_b_munmap},
    {"nanosleep", (uintptr_t)sym_b_nanosleep},
    {"open", (uintptr_t)sym_b_open},
    {"opendir", (uintptr_t)sym_b_opendir},
    {"pclose", (uintptr_t)sym_b_pclose},
    {"perror", (uintptr_t)sym_b_perror},
    {"pipe", (uintptr_t)sym_b_pipe},
    {"poll", (uintptr_t)sym_b_poll},
    {"popen", (uintptr_t)sym_b_popen},
    {"pow", (uintptr_t)sym_pow},
    {"powf", (uintptr_t)sym_powf},
    {"prctl", (uintptr_t)sym_b_prctl},
    {"printf", (uintptr_t)sym_b_printf},
    {"pthread_attr_destroy", (uintptr_t)sym_b_pthread_attr_destroy},
    {"pthread_attr_getdetachstate", (uintptr_t)sym_b_pthread_attr_getdetachstate},
    {"pthread_attr_getstack", (uintptr_t)sym_b_pthread_attr_getstack},
    {"pthread_attr_init", (uintptr_t)sym_b_pthread_attr_init},
    {"pthread_attr_setdetachstate", (uintptr_t)sym_b_pthread_attr_setdetachstate},
    {"pthread_attr_setschedparam", (uintptr_t)sym_b_pthread_attr_setschedparam},
    {"pthread_attr_setschedpolicy", (uintptr_t)sym_b_pthread_attr_setschedpolicy},
    {"pthread_attr_setstacksize", (uintptr_t)sym_b_pthread_attr_setstacksize},
    {"pthread_cond_broadcast", (uintptr_t)sym_b_pthread_cond_broadcast},
    {"pthread_cond_destroy", (uintptr_t)sym_b_pthread_cond_destroy},
    {"pthread_cond_init", (uintptr_t)sym_b_pthread_cond_init},
    {"pthread_cond_signal", (uintptr_t)sym_b_pthread_cond_signal},
    {"pthread_cond_timedwait", (uintptr_t)sym_b_pthread_cond_timedwait},
    {"pthread_cond_timedwait_monotonic_np", (uintptr_t)sym_b_pthread_cond_timedwait_monotonic_np},
    {"pthread_cond_wait", (uintptr_t)sym_b_pthread_cond_wait},
    {"pthread_create", (uintptr_t)sym_b_pthread_create},
    {"pthread_detach", (uintptr_t)sym_b_pthread_detach},
    {"pthread_equal", (uintptr_t)sym_b_pthread_equal},
    {"pthread_exit", (uintptr_t)sym_b_pthread_exit},
    {"pthread_getattr_np", (uintptr_t)sym_b_pthread_getattr_np},
    {"pthread_getschedparam", (uintptr_t)sym_b_pthread_getschedparam},
    {"pthread_getspecific", (uintptr_t)sym_b_pthread_getspecific},
    {"pthread_join", (uintptr_t)sym_b_pthread_join},
    {"pthread_key_create", (uintptr_t)sym_b_pthread_key_create},
    {"pthread_key_delete", (uintptr_t)sym_b_pthread_key_delete},
    {"pthread_kill", (uintptr_t)sym_b_pthread_kill},
    {"pthread_mutex_destroy", (uintptr_t)sym_b_pthread_mutex_destroy},
    {"pthread_mutex_init", (uintptr_t)sym_b_pthread_mutex_init},
    {"pthread_mutex_lock", (uintptr_t)sym_b_pthread_mutex_lock},
    {"pthread_mutex_trylock", (uintptr_t)sym_b_pthread_mutex_trylock},
    {"pthread_mutex_unlock", (uintptr_t)sym_b_pthread_mutex_unlock},
    {"pthread_mutexattr_destroy", (uintptr_t)sym_b_pthread_mutexattr_destroy},
    {"pthread_mutexattr_init", (uintptr_t)sym_b_pthread_mutexattr_init},
    {"pthread_mutexattr_settype", (uintptr_t)sym_b_pthread_mutexattr_settype},
    {"pthread_once", (uintptr_t)sym_b_pthread_once},
    {"pthread_self", (uintptr_t)sym_b_pthread_self},
    {"pthread_setname_np", (uintptr_t)sym_b_pthread_setname_np},
    {"pthread_setschedparam", (uintptr_t)sym_b_pthread_setschedparam},
    {"pthread_setspecific", (uintptr_t)sym_b_pthread_setspecific},
    {"pthread_sigmask", (uintptr_t)sym_b_pthread_sigmask},
    {"ptrace", (uintptr_t)sym_b_ptrace},
    {"putc", (uintptr_t)sym_b_putc},
    {"putchar", (uintptr_t)sym_b_putchar},
    {"puts", (uintptr_t)sym_b_puts},
    {"putwc", (uintptr_t)sym_b_putwc},
    {"qsort", (uintptr_t)sym_qsort},
    {"raise", (uintptr_t)sym_b_raise},
    {"read", (uintptr_t)sym_b_read},
    {"readdir", (uintptr_t)sym_b_readdir},
    {"readlink", (uintptr_t)sym_b_readlink},
    {"realloc", (uintptr_t)sym_realloc},
    {"recv", (uintptr_t)sym_b_recv},
    {"recvfrom", (uintptr_t)sym_b_recvfrom},
    {"recvmsg", (uintptr_t)sym_b_recvmsg},
    {"rename", (uintptr_t)sym_b_rename},
    {"rint", (uintptr_t)sym_b_rint},
    {"rmdir", (uintptr_t)sym_b_rmdir},
    {"round", (uintptr_t)sym_b_round},
    {"roundf", (uintptr_t)sym_b_roundf},
    {"sched_get_priority_max", (uintptr_t)sym_b_sched_get_priority_max},
    {"sched_get_priority_min", (uintptr_t)sym_b_sched_get_priority_min},
    {"sched_yield", (uintptr_t)sym_b_sched_yield},
    {"select", (uintptr_t)sym_b_select},
    {"sem_destroy", (uintptr_t)sym_b_sem_destroy},
    {"sem_getvalue", (uintptr_t)sym_b_sem_getvalue},
    {"sem_init", (uintptr_t)sym_b_sem_init},
    {"sem_post", (uintptr_t)sym_b_sem_post},
    {"sem_timedwait", (uintptr_t)sym_b_sem_timedwait},
    {"sem_trywait", (uintptr_t)sym_b_sem_trywait},
    {"sem_wait", (uintptr_t)sym_b_sem_wait},
    {"send", (uintptr_t)sym_b_send},
    {"sendfile", (uintptr_t)sym_b_sendfile},
    {"sendmsg", (uintptr_t)sym_b_sendmsg},
    {"sendto", (uintptr_t)sym_b_sendto},
    {"setenv", (uintptr_t)sym_b_setenv},
    {"setitimer", (uintptr_t)sym_b_setitimer},
    {"setjmp", (uintptr_t)sym_b_setjmp},
    {"setlocale", (uintptr_t)sym_b_setlocale},
    {"setpriority", (uintptr_t)sym_b_setpriority},
    {"setresuid", (uintptr_t)sym_b_setresuid},
    {"setsockopt", (uintptr_t)sym_b_setsockopt},
    {"setvbuf", (uintptr_t)sym_b_setvbuf},
    {"shutdown", (uintptr_t)sym_b_shutdown},
    {"sigaction", (uintptr_t)sym_b_sigaction},
    {"siglongjmp", (uintptr_t)sym_b_siglongjmp},
    {"sigprocmask", (uintptr_t)sym_b_sigprocmask},
    {"sigsetjmp", (uintptr_t)sym_b_sigsetjmp},
    {"sigsuspend", (uintptr_t)sym_b_sigsuspend},
    {"sin", (uintptr_t)sym_sin},
    {"sinf", (uintptr_t)sym_sinf},
    {"sinh", (uintptr_t)sym_sinh},
    {"sleep", (uintptr_t)sym_b_sleep},
    {"snprintf", (uintptr_t)sym_b_snprintf},
    {"socket", (uintptr_t)sym_b_socket},
    {"sprintf", (uintptr_t)sym_b_sprintf},
    {"sqrt", (uintptr_t)sym_b_sqrt},
    {"sqrtf", (uintptr_t)sym_b_sqrtf},
    {"srand48", (uintptr_t)sym_srand48},
    {"sscanf", (uintptr_t)sym_sscanf},
    {"stat", (uintptr_t)sym_b_stat},
    {"strcasecmp", (uintptr_t)sym_strcasecmp},
    {"strcasestr", (uintptr_t)sym_strcasestr},
    {"strcat", (uintptr_t)sym_strcat},
    {"strchr", (uintptr_t)sym_strchr},
    {"strcmp", (uintptr_t)sym_strcmp},
    {"strcoll", (uintptr_t)sym_strcoll},
    {"strcpy", (uintptr_t)sym_strcpy},
    {"strdup", (uintptr_t)sym_strdup},
    {"strerror", (uintptr_t)sym_b_strerror},
    {"strftime", (uintptr_t)sym_b_strftime},
    {"strlcpy", (uintptr_t)sym_strlcpy},
    {"strlen", (uintptr_t)sym_strlen},
    {"strncasecmp", (uintptr_t)sym_strncasecmp},
    {"strncat", (uintptr_t)sym_strncat},
    {"strncmp", (uintptr_t)sym_strncmp},
    {"strncpy", (uintptr_t)sym_strncpy},
    {"strpbrk", (uintptr_t)sym_strpbrk},
    {"strrchr", (uintptr_t)sym_strrchr},
    {"strsep", (uintptr_t)sym_strsep},
    {"strstr", (uintptr_t)sym_strstr},
    {"strtod", (uintptr_t)sym_strtod},
    {"strtok", (uintptr_t)sym_strtok},
    {"strtok_r", (uintptr_t)sym_strtok_r},
    {"strtol", (uintptr_t)sym_strtol},
    {"strtoul", (uintptr_t)sym_strtoul},
    {"strtoull", (uintptr_t)sym_strtoull},
    {"strxfrm", (uintptr_t)sym_strxfrm},
    {"swscanf", (uintptr_t)sym_swscanf},
    {"syscall", (uintptr_t)sym_b_syscall},
    {"sysconf", (uintptr_t)sym_b_sysconf},
    {"system", (uintptr_t)sym_b_system},
    {"tan", (uintptr_t)sym_tan},
    {"tanf", (uintptr_t)sym_tanf},
    {"tanh", (uintptr_t)sym_tanh},
    {"time", (uintptr_t)sym_b_time},
    {"tkill", (uintptr_t)sym_b_tkill},
    {"tolower", (uintptr_t)sym_tolower},
    {"towlower", (uintptr_t)sym_towlower},
    {"towupper", (uintptr_t)sym_towupper},
    {"trunc", (uintptr_t)sym_b_trunc},
    {"truncate", (uintptr_t)sym_b_truncate},
    {"truncf", (uintptr_t)sym_b_truncf},
    {"uname", (uintptr_t)sym_b_uname},
    {"ungetc", (uintptr_t)sym_b_ungetc},
    {"ungetwc", (uintptr_t)sym_b_ungetwc},
    {"unlink", (uintptr_t)sym_b_unlink},
    {"unsetenv", (uintptr_t)sym_b_unsetenv},
    {"usleep", (uintptr_t)sym_b_usleep},
    {"utime", (uintptr_t)sym_b_utime},
    {"vasprintf", (uintptr_t)sym_b_vasprintf},
    {"vfprintf", (uintptr_t)sym_b_vfprintf},
    {"vprintf", (uintptr_t)sym_b_vprintf},
    {"vsnprintf", (uintptr_t)sym_b_vsnprintf},
    {"vsprintf", (uintptr_t)sym_b_vsprintf},
    {"waitpid", (uintptr_t)sym_b_waitpid},
    {"wcrtomb", (uintptr_t)sym_b_wcrtomb},
    {"wcscat", (uintptr_t)sym_wcscat},
    {"wcscmp", (uintptr_t)sym_wcscmp},
    {"wcscoll", (uintptr_t)sym_wcscoll},
    {"wcscpy", (uintptr_t)sym_wcscpy},
    {"wcsftime", (uintptr_t)sym_b_wcsftime},
    {"wcslen", (uintptr_t)sym_wcslen},
    {"wcsncat", (uintptr_t)sym_wcsncat},
    {"wcsncmp", (uintptr_t)sym_wcsncmp},
    {"wcsncpy", (uintptr_t)sym_wcsncpy},
    {"wcstod", (uintptr_t)sym_wcstod},
    {"wcstol", (uintptr_t)sym_wcstol},
    {"wcsxfrm", (uintptr_t)sym_wcsxfrm},
    {"wctob", (uintptr_t)sym_b_wctob},
    {"wctype", (uintptr_t)sym_wctype},
    {"wmemchr", (uintptr_t)sym_wmemchr},
    {"wmemcmp", (uintptr_t)sym_wmemcmp},
    {"wmemcpy", (uintptr_t)sym_wmemcpy},
    {"wmemmove", (uintptr_t)sym_wmemmove},
    {"wmemset", (uintptr_t)sym_wmemset},
    {"wprintf", (uintptr_t)sym_b_wprintf},
    {"write", (uintptr_t)sym_b_write},
    {"writev", (uintptr_t)sym_b_writev},
    {"", 0},
};

int dcr_imports_count = (int)(sizeof(dcr_imports) / sizeof(dcr_imports[0])) - 1;
